# Generated by Xplorer, do not modify.
# This Makefile builds _single_build Debug

%:: RCS/%,v
%:: RCS/%
%:: s.%
%:: SCCS/s.%
.SUFFIXES:
.SUFFIXES: .a .o .c .cc .C .cpp .s .S .h


# There should not be an 'sh.exe' in path
export SHELL = cmd


# There should never be any unknown unix-like tools on the path
# In particular there should not be an 'sh.exe' in the system32 directory
export PATH = C:\usr\xtensa\XtDevTools\install\tools\RI-2019.1-win32\XtensaTools\bin\;C:\usr\xtensa\XtDevTools\install\tools\RI-2019.1-win32\XtensaTools\lib\iss\;C:\Windows\system32

all:
	cmd /c "cd /D ""C:\\usr\\xtensa\\Xplorer-8.0.10-workspaces\\workspace\\Task7_AE\\bin\\hifi3_bd5\\Debug"" && $(MAKE) all  "

clean:
	cmd /c "cd /D ""C:\\usr\\xtensa\\Xplorer-8.0.10-workspaces\\workspace\\Task7_AE\\bin\\hifi3_bd5\\Debug"" && $(MAKE) clean  "
